# For MYSQL container
DOCKER_MYSQL_USER: "root"
DOCKER_MYSQL_PASSWORD: "webdevel"
# DOCKER_MYSQL_HOST: "192.168.99.100"
# For linux, use the 127.0.0.1 as the host for windows use the docker host IP
DOCKER_MYSQL_HOST: "127.0.0.1"
DOCKER_MYSQL_PORT: "3306"
DOCKER_MYSQL_DB: "rorstudentapp?"

# For local
# DOCKER_MYSQL_HOST: "localhost"
# DOCKER_MYSQL_PORT: "3306"
